### ISSUE TITLE
Fil de discussion sur la page d'une géocache

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#11]
Objectif : permettre aux participants de faire des commentaires, write note, échanges autour de leur trouvaille

**Comment by flapouille** [comment]
également sur la page des TB ?

**Comment by MariusMez** [comment]
Si on veux, ce sera simple à intégrer, cf commit https://github.com/MariusMez/GeocachingJDS/commit/1a0bba821fda92af63e6d32c2eceb1ba6b63d235
