### ISSUE TITLE
Faire une liste de mission

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#13]
En plus d'une mission à renseigner par l'owner, nous pouvons proposer une liste de missions pré-établies qui permettrons de comptabiliser les scores plus simplement.

Cette liste pourrait être présentée sous forme de cases à cocher par le propriétaire dans le profil/ page de création du TB.

Les photos devront nous permettre de valider la bonne réussite des missions (cela restera subjectif, mais tjr plus facile que coder un système d'attribution automatique des points)

**Comment by flapouille** [comment]
je suis d'accord de mettre une liste fixe de mission car on a pu voir sur notre premiere participatrice que sa mission était loin d'être faisable ! 
On pourra préciser que des idées de mission peuvent nous etre soumise pour que l'on les ajoute.

**Comment by MariusMez** [comment]
@flapouille : Ok, concernant la liste des missions, pour rester simple le mieux est je pense de ne pas modifier le formulaire actuel de création des TBs.

Il y a une ligne "mission", que j'ai renommée en "mission personnelle" avec une note invitant à écrire quelque chose de réaliste. Je vois plus cette "mission "personnelle" comme un rôle à jouer par le TB (c'est plus philosophique que pour la course).

Concernant les "vraies missions" que nous avons en tête (distance parcourus max, nombre d'échanges, de photos sur le terrain avec des orga, ...) le mieux est amha de les lister en tête des régles et de dire que un TB en course peut accomplir de 0 à toutes ces missions et que chaque mission accomplie (en fait c'est plus trop des missions) débloque un certain nombre de points.

Leur permettre de choisir les missions qu'ils souhaitent accomplir pour le comptage des points avec des démultiplicateurs sera trop complexe  je pense.

**Comment by flapouille** [comment]
euhh je crois qu'on est pas tres aligné sur ce sujet ;). 
Je pousse la pull request concernant les regles du jeux comme ça tu verras ce que j'avais en tete. c'est surtout quelque chose de simple qui donne envie de faire bouger les objets et faire des photos sympa. rien de tres complexe. 
pour les missions, je vais juste mettre un texte pour aider à bien choisir sa mission. rien de plus. ça reste un texte libre. si la mission est infaisable (comme celle de ton Nain.... ;) ) , personne ne pourra la réaliser.

**Comment by flapouille** [comment]
n'hésite pas à commenter avant de merger.

**Comment by MariusMez** [comment]
Ok, je te laisse créer la pull request au préalable ;-)

**Comment by flapouille** [comment]
pull request lancé. j'ai enlevé la partie ou tu répondais aux questions sur les TB car on utilise pas les meme regles pour le jeu.

**Comment by MariusMez** [comment]
Je peux closer ?
