### ISSUE TITLE
Gérer les cas tordus de Drop/Grab TB

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#17]
// TODO : gérer le cas ou le TB est présent dans une cache
// Ajouter l'option dans le select : Récupérer dans la cache : nom de la cache
// Gérer les cas d'erreur Grab depuis une autre cache que celui dans lequel il est affecté dans la BDD

**Comment by MariusMez** [comment]
TODO : verifier que la personne qui droppe est bien le holder.

**Comment by flapouille** [comment]
j'ai ajouté une notion d'identification via le email. 
j'ai désactivé le bouton de drop/grab sur la page du TB : tout passe par le flashIt. c'est plus simple et ca évite les cas complexes.

**Comment by flapouille** [comment]
j'ai ajouté un check au moment de la création d'un objet pour etre sur qu'il n'y a pas deux objets avec le meme email.

**Comment by MariusMez** [comment]
j'ai désactivé le bouton de drop/grab sur la page du TB : tout passe par le flashIt. c'est plus simple et ca évite les cas complexes.

--> Ok mais tu es sûre que c'est réellement plus simple de tout centraliser sur le QRCode du flashit ?

**Comment by MariusMez** [comment]
Je réouvre pour plusieurs questions:

- C'est volontaire sur la page foundittb dans le cas d'un grab de TB de ne pas afficher la partie message / photo / fav du formulaire ?

- Dans le cas d'un flashit/ première fois à trouver la boite --> formulaire found : on n'a pas directement la possibilité de grab/drop des TBs à l'issue du found, il me semblait que c'était prévu ? Seule possibilité actuellement : reflasher le qrcode pour être redirigé sur le logtb

**Comment by MariusMez** [comment]
J'ai volontairement pas affiché la photo sur la page de foundtb pour ne pas alourdir le chargement en mobilité, j'ai affiché le Code du TB à la place (il est bien vérifié oui)

J'ai refactoré le code du found il y avait quelques petits bugs, c'est normalement tout bon dorénavant
