### ISSUE TITLE
Page de validation des missions

### ISSUE THREAD

**Issue by flapouille** [MariusMez/GeocachingJDS#18]
pouvoir voir ses TBs 
pour chaque TB possédé, voir les photos liées a la mission et valider les missions.

**Comment by flapouille** [comment]
lorsque l'attribut "Mission" n'existe pas dans TravelbugLog, c'est que la mission n'a pas été encore validé. lorsqu'on valide on met 0 si mission pas satisfaite, 1 si mission satisfaite. 
il faudrait donc faire une page pour regarder les photos qui n'ont pas l'attribut Mission, et pouvoir valider et invalider les missions.

**Comment by flapouille** [comment]
si tu veux t'en occuper, c'est avec plaisir ;) c'est un peu similaire à l'issue #10

**Comment by MariusMez** [comment]
Ok, on est d'accord que c'est que pour nous cette page ?

**Comment by flapouille** [comment]
si on mets -1 ça enleve des points dans le score pour le moment. 
oui, que pour nous. j'ai pensé qu'on aurait pu donner la main au propriétaire du tb mais c'est galere vu le manque d'identification.

**Comment by MariusMez** [comment]
Ok, par contre pour le calcul des score c'est mieux si tu considères cet attribut mission comme un three state boolean et ensuite au moment où tu calcules le score tu utilises un coefficient (que tu peux coder en dur)

**Comment by MariusMez** [comment]
Implémenté ici : https://www.geocaching-jds.fr/missionvalidator (page publique pour le moment, reste à mettre une restriction d'accès sur le NGinx)
