### ISSUE TITLE
Mettre à jour le classement avec prise en compte du score TB

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#26]
Mettre à jour la page de listing des TB pour ajouter une colonne score

Ajouter une colonne scoreTB au classement général avec le report du score du listing TB

**Comment by flapouille** [comment]
pour les lignes de type "drop"
* ajout d'une colonne score (remplie selon si le tb est rencontré pour la premiere fois par le joueur ou si le tb rencontre pour la premiere fois la cache). 
* ajout d'une colonne mission (remplie si le log satisfait la mission ou pas)

prise en compte de ces 2 colonnes dans le calcul du classement

**Comment by flapouille** [comment]
j'ai modifié le code pour calcul des notions de FTF , STF, ... ainsi que les aspects relatifs au voyage des TB en temps réel. 
le calcul de myscore est opérationel. 
par contre je n'ai pas fait le score pour tous les concurrents. je crerai une nouvelle carte.

**Comment by MariusMez** [comment]
Je pense qu'il faut pas s'embêter avec la page myscore, la fonctionnalité existe déjà à travers le tableau du classement sur la page ranking

**Comment by flapouille** [comment]
je comprends, par contre c'est plus simple à corriger les cas ou ça se passe pas bien , plutot que de systématiquement saisir à la main; non?

**Comment by MariusMez** [comment]
Sans doute, mais en l'état faudra faire les 2 :D

**Comment by MariusMez** [comment]
Il faudrait ajouter une relation entre la classe Ranking et un pointer vers un champ Geocacheur de la classe Geocacheur

**Comment by MariusMez** [comment]
Voilà c'est fait, il y a un lien entre les tables Geocacheur et Ranking (qui se mettra à jour toute seule) et il restera seulement à compléter à la main dans la table Ranking les parties FTF/STF/TTF avec des chiffres qui s'incrémentent pour chaque participant (j'ai laissé le champ email pour trouver plus facilement le participant dans le dashboard de parse).
