### ISSUE TITLE
Création du TB

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#4]
Déclarer son tb. ca donne un code unique de participant + un code pour le tb

Nom du TB (visible à tous):
Pseudo du propriétaire (visible à tous) :  
Email du propriétaire (privé) :
Description (visible à tous) : 

Code unique TB (visible à tous): 
Code unique propriétaire (privé) :

**Comment by flapouille** [comment]
Je n'ai pas l'air de pouvoir me l'assigner :)
