### ISSUE TITLE
Ajout bouton GRAB/DROP sur la page de profil du TB

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#43]
Après discussion avec les utilisateurs, nombreux sont ceux qui captent pas bien à sophia (et donc certains pensent à prendre le QR en photo, mais pas tous)

Aussi je pense que le risque est grand que certains prennent des TB sans shooter le QRCode pour le Grab et se contente du Drop ailleurs (ce qui posera problème)

Remettre le bouton comme c'était avant va pe éviter ça
@flapouille ton avis ?

**Comment by flapouille** [comment]
je comprends .. le probleme est le meme avec le log de la cache non? peut etre que c'est l'url du flashit qu'il faut mettre, plutot que de remettre le bouton au niveau du TB?

**Comment by MariusMez** [comment]
C'est le plus simple en effet, mais du coup on permet potentiellement de faire des log depuis chez soit,  ça nous obligera à potentiellement vérifier les logbooks, mais c'est plus dans l'esprit du géocaching

Je suis pour ton idée

**Comment by MariusMez** [comment]
Mais d'abord attendons de voir si les hypothèses imaginées vont se réaliser

**Comment by flapouille** [comment]
ok. ton message d'origine me laissait penser que c'était déja un probleme ? :)

**Comment by MariusMez** [comment]
Je close, ça semble pas utile finalement vu que les gens font des logs de chez eux :D
