### ISSUE TITLE
Préciser de ne pas mettre le code du TB sur ses photos

### ISSUE THREAD

**Issue by flapouille** [MariusMez/GeocachingJDS#44]
j'ai mis à jour le descriptif de la cache point de départ, mais il faudrait le mettre à d'autres endroits + eventuellement renvoyer un mail à tous le monde.

**Comment by MariusMez** [comment]
J'avais déjà ajouté cette mention dans le register TB, pas utile à mon avis d'en faire plus, je close.

Y aura tjr des boulets de toute façon :D

**Comment by flapouille** [comment]
et ça a été ajouté au moment du log pour la mission du TB?

**Comment by MariusMez** [comment]
Yep mais pas commit, ma faute
