### ISSUE TITLE
bug tb

### ISSUE THREAD

**Issue by flapouille** [MariusMez/GeocachingJDS#49]
* autoriser les drop meme si on a plus de 4 objets
* bloquer le grab si on a 3 objets
* flag newCache uniquement sur le premier log

**Comment by MariusMez** [comment]
Peut-être aussi remettre la limite de posession a deux tb max, j’avais mis a trois pensant que ca permettrait d’eviTer d’engorGer les boites mais visiblement les gens préfèrent faire transiter les tb...

**Comment by flapouille** [comment]
je propose de rester sur 3 pour ne pas perturber tout le monde avec des changements de règles...
