### ISSUE TITLE
Retrieve/Drop/Discover un TB sur page de foundIt

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#5]
Quand on loggue, ajouter dans le formulaire la possibilité de :

- Dropper un TB en saisissant son n°
- Récupérer un TB en saisissant son n°

optionnel : Discover mais ça peut compliquer les choses et provoquer des erreurs des utilisateurs, je suis pas spécialement pour

**Comment by flapouille** [comment]
Je ne suis pas non plus de faire le "discover". 
par contre, pour je suis pour avoir une liste de TB dynamique (si drop = liste des codes des TB possédés par le pseudo, si grab = liste des TB dans la cache). 
Il faut pouvoir logguer la meme cache plusieurs fois .. il y a besoin de faire une évo pour ne pas compter les points 2 fois ?

**Comment by MariusMez** [comment]
Oui la liste semble le bon truc à faire pour que ce soit pratique à utiliser.

Par contre rien n'empêche de logguer la cache plusieurs fois (d'ailleurs ça arrive bien souvent quand les gens scannent le QRcode plusieurs fois en pensant que ca ne fonctionnait pas à cause d'un réseau pourri avec free...). Jusqu'à présent j'éditait manuellement la base pour supprimer les doublons.

Du coup si tu souhaites qu'on puisse logguer deux fois les caches il faudra soit modifier la requête du script de calcul des points pour ne pas comptabiliser les doublons, soit détecter au préalable le doublon et le transformer en équivalent des write note comme le fait le site géocaching.

Mais le plus simple reste dans un premier temps de pas traiter spécialement ce cas ou la personne retourne 2 fois visiter la cache. Ou alors il faut dissocier ça du foundit

**Comment by MariusMez** [comment]
J'ai commencé à développer cette fonctionnalité, il s'avère que c'est plus complexe qu'imaginé à la base sans implémenter de système de login/authentification.

Cela reste possible de lister les TBs dans la cache pour le grab

Mais pour le drop cela nécessite de connaitre le pseudo de l'owner pour lister les TB de l'owner, cela implique donc de redemander la saisie du pseudo (ce qui est fait dans le formulaire, mais pas encore soumis, donc de faire un genre de requete ajax )

Bref cela devient compliqué à coder, et sans doute aussi compliquer à utiliser au niveau interface surtout si les listes des TBs sont longues. Et il risque d'y avoir plein d'erreurs de manipulation.

Je propose donc de garder l'interface de foundit actuelle et d'ajouter sur la page des objets voyageurs un formulaire spécifique comme sur la page https://www.geocaching.com/track/ et qui permettra au cas par cas avec un code de TB 

Sinon j'ai peur de pas y arriver

**Comment by MariusMez** [comment]
J'ai poussé sur la branche edition2018 une nouvelle version ;-)

**Comment by flapouille** [comment]
je suis pas hyper fan ; je trouve ça plus compliqué à expliquer comme workflow mais peut etre plus simple pour la maintenance.

**Comment by MariusMez** [comment]
Ok super, faudra sans doute rajouter l'option : "le prendre d'ailleurs / des mains d'un autre géocacheur" dans le cas ou il aurait transité sans être loggué

**Comment by MariusMez** [comment]
Je close pour le moment pour faire un peu de ménage dans la liste, on pourra le réouvrir si besoin
