### ISSUE TITLE
Permettre de renseigner son Pseudo de participant lors du premier log

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#70]
Lors du premier log, permettre au participant de définir son pseudo au moment du premier found-it

**Comment by NassimBounouas** [comment]
Bonjour,

J'ai implémenté la fonctionnalité de manière à ajouter un champ pour spécifier un pseudo lors du premier log et de l'utiliser pour ce log tout en mettant à jour le "profil" géocacheur pour que le pseudo soit réutilisé lors des suivants.

Actuellement la présence du pseudo n'est vérifiée que dans le front. Une petite inspection et modification du DOM permet de faire le premier log sans spécifier de Pseudo.

@MariusMez : Dans le cas d'une vérification du pseudo dans le back, une préférence pour le comportement à adopter ? Retour sur la page de log ou retour à l'accueil ?

Merci

**Comment by MariusMez** [comment]
@NassimBounouas tu évoques quel cas de vérification ? Pour rester simple, si retour à l'accueil si on sort du "cas d'usage normal"

J'ai mis un commentaire sur le render 'foundit' dans la fonction found qui me semblait pas opportun, à vérifier

**Comment by MariusMez** [comment]
Merci @NassimBounouas, je cloture ;-)
