### ISSUE TITLE
Ajout zone TB dans la page d'une Géocache

### ISSUE THREAD

**Issue by MariusMez** [MariusMez/GeocachingJDS#8]
Sur la page d'une cache, les tb qui ont visités , les tb présents

**Comment by flapouille** [comment]
en plus de ça, j'ai mis les évenements de la vie d'un TB, et j'ai également retravaillé légèrement la façon de faire les drop et les grab. c'est lorsque le holder est non null que l'on peut faire un drop, et lorsque le tb est dans une cache que l'on peut faire un grab. ça permet d'avoir un peu plus de logique dans le workflow. 

TODO : verifier que la personne qui droppe est bien le holder.

**Comment by MariusMez** [comment]
Top, je close cet issue pour le moment, le todo aura sa propre issue
